name: adminapp
description: A new Flutter project.
homepage: https://github.com/aleksanderwozniak/table_calendar
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  flutter_lints: ^2.0.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.2.5
  flutter_svg: ^0.22.0
  google_fonts: ^5.1.0
  flutter_localizations:
    sdk: flutter
  pretty_qr_code: ^2.0.3
  http: ^1.0.0
  logger: ^1.1.0
  vertical_barchart: ^2.0.0+2
  data_table_2: ^2.5.6
  provider: ^6.0.1
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  collapsible_sidebar: ^2.0.5+1
  side_navigation: ^1.0.4
  custom_date_range_picker: ^1.0.10
  shared_preferences: ^2.2.0
  usb_serial: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true        
  assets:
    - assets/page-1/images/h.png
    - assets/page-1/images/frame-12.png
    - assets/page-1/images/component-2.png
    - assets/page-1/images/frame-13.png
    - assets/page-1/images/frame-11.png
    - assets/page-1/images/frame-15.png
    - assets/page-1/images/frame-14.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-mW9.png
    - assets/page-1/images/vector-Mtd.png
    - assets/page-1/images/vector-kCH.png
    - assets/page-1/images/vector-tW5.png
    - assets/page-1/images/vector-ZW9.png
    - assets/page-1/images/component-3.png
    - assets/page-1/images/vector-oBF.png
    - assets/page-1/images/vector-N7j.png
    - assets/page-1/images/image-7-bg.png
    - assets/page-1/images/vector-K53.png
    - assets/page-1/images/-yWy.png
    - assets/page-1/images/icon-park-outline-buy.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/group-585.png
    - assets/page-1/images/-9eZ.png
    - assets/page-1/images/component-4.png
    - assets/page-1/images/-yso.png
    - assets/page-1/images/formkit-won.png
    - assets/page-1/images/-sSh.png
    - assets/page-1/images/fluent-person-walking-16-regular.png
    - assets/page-1/images/on.png
    - assets/page-1/images/-d4M.png
    - assets/page-1/icons/frame-12.ico
    - assets/page-1/images/-c8Z.png
    - assets/page-1/images/-UrD.png
    - assets/page-1/images/-Ysj.png
    - assets/page-1/images/-Hnh.png
    - assets/page-1/images/-YR7.png
    - assets/page-1/images/-Nf3.png
    - assets/page-1/images/-Tn9.png
    # - assets/page-1/images/-EVP.png
    - assets/page-1/images/group-12777.png
    - assets/page-1/images/group-12778.png
    - assets/page-1/images/group-12777-zGq.png
    - assets/page-1/images/mingcute-search-line.png
    # - assets/page-1/images/-E8y.png
    - assets/page-1/images/-8QR.png
    - assets/page-1/images/free-icon-turnstile-6361193-1-bg.png
    - assets/page-1/images/free-icon-turnstile-6361193-1-bg-C6u.png
    - assets/page-1/images/in.png
    - assets/page-1/images/out.png
    - assets/page-1/images/sunban.png
    - assets/page-1/images/sunban2.png
    - assets/page-1/images/Lunchcase.png
    - assets/page-1/images/Freezer.png
    - assets/page-1/images/Fridge.png
    - assets/page-1/images/Shelf.png
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/_NanumSquareNeo-cBd.ttf


# _NanumSquareNeo-cBd